default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: pwd
  host: localhost

development:
  <<: *default
  database: poc-dev

test:
  <<: *default
  database: poc-test

production:
  <<: *default
  database: poc-prod
